### PR TITLE
Add linguist-language=C++ to .gitattributes

### PR DESCRIPTION
**Pull request by wroyca**
This PR enhances the .gitattributes generation code by adding the linguist-language=C++ attribute. This attribute ensures that Git repository hosting platforms correctly recognize txx and ixx file types, which are not detected as C++ by default.

### CODE REVIEW

**Comment by boris-kolpackov** [comment]
Background: this appears to be GitHub-only, based on their https://github.com/github/linguist Ruby library.

Maybe we can also add this for our `buildfile`s (which currently seem to be treated as Ruby).

**Comment by wroyca** [comment]
> Background: this appears to be GitHub-only, based on their https://github.com/github/linguist Ruby library.
> 
> Maybe we can also add this for our `buildfile`s (which currently seem to be treated as Ruby).

This is also used by GitLab https://gitlab.com/gitlab-org/linguist and others~ 🙂

**Comment by wroyca** [comment]
> Maybe we can also add this for our `buildfile`s (which currently seem to be treated as Ruby).

We can use linguist-language=Makefile for build2 related files. You may add new commits to my branch if you feel like it's something we should have - or just give me a ping, and I'll take a look at it when I'm available! :rocket:

**Comment by wroyca** [comment]
Closing as this will be merged with github-linguist next release.

**Pull request closed without merging**
